# Dependencies

In [2]:
import pandas as pd
import numpy as np

In [3]:
list_s = [1,2,-3,6.2, 'Data Values']
series1 = pd.Series(list_s)
series1

0              1
1              2
2             -3
3            6.2
4    Data Values
dtype: object

In [5]:
type(series1)

pandas.core.series.Series

In [12]:
series2 = pd.Series(
    [9,7,6,5,4], 
    index=['a','b','c','d','e'],
    dtype= float,
    name="Data Values"
)
series2

a    9.0
b    7.0
c    6.0
d    5.0
e    4.0
Name: Data Values, dtype: float64

In [15]:
scalar_s = pd.Series(0.5, index = [1,2,3])
scalar_s

1    0.5
2    0.5
3    0.5
dtype: float64

In [18]:
dict_s = pd.Series({'a':1, "b":2, 'c':3})
dict_s

a    1
b    2
c    3
dtype: int64

# Operators

In [20]:
series1[2]

-3

In [23]:
series1[0:3]

0     1
1     2
2    -3
dtype: object

In [26]:
max(series2)

9.0

In [29]:
series2[series2>6]

a    9.0
b    7.0
Name: Data Values, dtype: float64

In [32]:
series2 + dict_s

a    10.0
b     9.0
c     9.0
d     NaN
e     NaN
dtype: float64

# Pandas DataFrame

In [35]:
empty_df = pd.DataFrame()
print(empty_df)

Empty DataFrame
Columns: []
Index: []

In [40]:
lst = ['a','b','c']


df1 = pd.DataFrame (lst)
df1

   0
0  a
1  b
2  c

In [42]:
lst_of_lst = [[1,2,3], [4,5,6],[7,8,9]]
df2 = pd.DataFrame(lst_of_lst)
df2

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [46]:
dict1 = {'ID' : [11,22,33,44], 'SN' : [1,2,3,4]}

df3 = pd.DataFrame(dict1)
df3

   ID  SN
0  11   1
1  22   2
2  33   3
3  44   4

In [50]:
ls_dict  = [{'a':1 , 'b':2}, {'a':3, 'b' : 4, 'c': 5}]

df5 = pd.DataFrame(ls_dict)
df5

   a  b    c
0  1  2  NaN
1  3  4  5.0

In [54]:
dict_sr = {'ID' : pd.Series([1,2,3]), 'SN': [111,222,333]}
df6 = pd.DataFrame(dict_sr)
df6

   ID   SN
0   1  111
1   2  222
2   3  333