# Dependencies

In [1]:
import pandas as pd

# Csv File Handeling

### Reading The file

In [8]:
df = pd.read_csv('bookdata.csv', nrows = 100 , usecols = [0,1,3,4,5,6,7,8])
df

,availability,category,no_of_reviews,product_type,stars,tax,title,total_price
0,19,music,0,books,5,0.0,Rip it Up and Start Again,35.02
1,19,business,0,books,4,0.0,The Dirty Little Secrets of Getting Your Dream...,33.34
2,19,young adult,0,books,1,0.0,The Requiem Red,22.65
3,19,poetry,0,books,4,0.0,Shakespeare's Sonnets,20.66
4,19,sequential art,0,books,5,0.0,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29
...,...,...,...,...,...,...,...,...
95,16,sequential art,0,books,4,0.0,"Outcast, Vol. 1: A Darkness Surrounds Him (Out...",15.44
96,16,history,0,books,2,0.0,"Political Suicide: Missteps, Peccadilloes, Bad...",36.28
97,16,sequential art,0,books,1,0.0,"Pop Gun War, Volume 1: Gift",18.97
98,16,fantasy,0,books,5,0.0,Princess Between Worlds (Wide-Awake Princess #5),13.34
99,16,sequential art,0,books,5,0.0,"Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...",13.61

In [9]:
df.columns

Index(['availability', 'category', 'no_of_reviews', 'product_type', 'stars',
       'tax', 'title', 'total_price'],
      dtype='object')

In [16]:
df_test = pd.read_csv(
    'bookdata.csv', 
    nrows = 100 , 
    usecols = [0,1,3,4,5,6,7,8],
    skiprows = [2,4],        # skiping Rows
    index_col= "title"    
)
df_test

,availability,category,no_of_reviews,product_type,stars,tax,total_price
title,,,,,,,
Rip it Up and Start Again,19,music,0,books,5,0.0,35.02
The Requiem Red,19,young adult,0,books,1,0.0,22.65
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1),19,sequential art,0,books,5,0.0,52.29
Set Me Free,19,young adult,0,books,5,0.0,17.46
"Starving Hearts (Triangular Trade Trilogy, #1)",19,default,0,books,2,0.0,13.99
...,...,...,...,...,...,...,...
"Pop Gun War, Volume 1: Gift",16,sequential art,0,books,1,0.0,18.97
Princess Between Worlds (Wide-Awake Princess #5),16,fantasy,0,books,5,0.0,13.34
"Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Princess Jellyfish 2-in-1 Omnibus #1)",16,sequential art,0,books,5,0.0,13.61
"Avatar: The Last Airbender: Smoke and Shadow, Part 3 (Smoke and Shadow #3)",16,fantasy,0,books,2,0.0,28.09
"Bitch Planet, Vol. 1: Extraordinary Machine (Bitch Planet (Collected Editions))",16,sequential art,0,books,2,0.0,37.92

In [27]:
df = pd.read_csv(
    'bookdata.csv', 
    nrows = 100 , 
    usecols = [0,1,3,4,5,6,7,8], 
    names= ['A','B','C','D','E','F','G','H']
)
df

,A,B,C,D,E,F,G,H
0,availability,category,no_of_reviews,product_type,stars,tax,title,total_price
1,19,music,0,books,5,0.0,Rip it Up and Start Again,35.02
2,19,business,0,books,4,0.0,The Dirty Little Secrets of Getting Your Dream...,33.34
3,19,young adult,0,books,1,0.0,The Requiem Red,22.65
4,19,poetry,0,books,4,0.0,Shakespeare's Sonnets,20.66
...,...,...,...,...,...,...,...,...
95,16,sequential art,0,books,3,0.0,Patience,10.16
96,16,sequential art,0,books,4,0.0,"Outcast, Vol. 1: A Darkness Surrounds Him (Out...",15.44
97,16,history,0,books,2,0.0,"Political Suicide: Missteps, Peccadilloes, Bad...",36.28
98,16,sequential art,0,books,1,0.0,"Pop Gun War, Volume 1: Gift",18.97
99,16,fantasy,0,books,5,0.0,Princess Between Worlds (Wide-Awake Princess #5),13.34

In [31]:
df = pd.read_csv(
    'bookdata.csv', 
    nrows = 100 , 
    usecols = [0,1,3,4,5,6,7,8], 
)
df.head(9)

,availability,category,no_of_reviews,product_type,stars,tax,title,total_price
0,19,music,0,books,5,0.0,Rip it Up and Start Again,35.02
1,19,business,0,books,4,0.0,The Dirty Little Secrets of Getting Your Dream...,33.34
2,19,young adult,0,books,1,0.0,The Requiem Red,22.65
3,19,poetry,0,books,4,0.0,Shakespeare's Sonnets,20.66
4,19,sequential art,0,books,5,0.0,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29
5,19,young adult,0,books,5,0.0,Set Me Free,17.46
6,19,default,0,books,2,0.0,"Starving Hearts (Triangular Trade Trilogy, #1)",13.99
7,20,history,0,books,5,0.0,Sapiens: A Brief History of Humankind,54.23
8,19,default,0,books,4,0.0,The Boys in the Boat: Nine Americans and Their...,22.60

In [39]:
df = pd.read_csv(
    'bookdata.csv', 
    nrows = 100 , 
    usecols = [0,1,3,4,5,7,8], 
    dtype= {'availability': 'float64'},
)
df.tail(9)

,availability,category,no_of_reviews,product_type,stars,title,total_price
91,16.0,add a comment,0,books,3,On a Midnight Clear,14.07
92,16.0,self help,0,books,1,Online Marketing for Busy Authors: A Step-By-S...,46.35
93,16.0,sequential art,0,books,1,orange: The Complete Collection 1 (orange: The...,48.41
94,16.0,sequential art,0,books,3,Patience,10.16
95,16.0,sequential art,0,books,4,"Outcast, Vol. 1: A Darkness Surrounds Him (Out...",15.44
96,16.0,history,0,books,2,"Political Suicide: Missteps, Peccadilloes, Bad...",36.28
97,16.0,sequential art,0,books,1,"Pop Gun War, Volume 1: Gift",18.97
98,16.0,fantasy,0,books,5,Princess Between Worlds (Wide-Awake Princess #5),13.34
99,16.0,sequential art,0,books,5,"Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...",13.61

### Writing Csv

In [47]:
df = pd.read_csv(
    'bookdata.csv', 
    nrows = 100 , 
    usecols = [0,1,3,4,5,7,8], 
    dtype= {'availability': 'float64'},
    na_values= ['sequential art', 'self help']
)
df.tail(8)

,availability,category,no_of_reviews,product_type,stars,title,total_price
92,16.0,NaN,0,books,1,Online Marketing for Busy Authors: A Step-By-S...,46.35
93,16.0,NaN,0,books,1,orange: The Complete Collection 1 (orange: The...,48.41
94,16.0,NaN,0,books,3,Patience,10.16
95,16.0,NaN,0,books,4,"Outcast, Vol. 1: A Darkness Surrounds Him (Out...",15.44
96,16.0,history,0,books,2,"Political Suicide: Missteps, Peccadilloes, Bad...",36.28
97,16.0,NaN,0,books,1,"Pop Gun War, Volume 1: Gift",18.97
98,16.0,fantasy,0,books,5,Princess Between Worlds (Wide-Awake Princess #5),13.34
99,16.0,NaN,0,books,5,"Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...",13.61

In [49]:
df.isnull().sum()

availability      0
category         15
no_of_reviews     0
product_type      0
stars             0
title             0
total_price       0
dtype: int64

In [51]:
df.dropna(axis = 1)

,availability,no_of_reviews,product_type,stars,title,total_price
0,19.0,0,books,5,Rip it Up and Start Again,35.02
1,19.0,0,books,4,The Dirty Little Secrets of Getting Your Dream...,33.34
2,19.0,0,books,1,The Requiem Red,22.65
3,19.0,0,books,4,Shakespeare's Sonnets,20.66
4,19.0,0,books,5,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29
...,...,...,...,...,...,...
95,16.0,0,books,4,"Outcast, Vol. 1: A Darkness Surrounds Him (Out...",15.44
96,16.0,0,books,2,"Political Suicide: Missteps, Peccadilloes, Bad...",36.28
97,16.0,0,books,1,"Pop Gun War, Volume 1: Gift",18.97
98,16.0,0,books,5,Princess Between Worlds (Wide-Awake Princess #5),13.34
99,16.0,0,books,5,"Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...",13.61

In [53]:
df.dropna(subset = ['category']).tail(7)

,availability,category,no_of_reviews,product_type,stars,title,total_price
87,16.0,food and drink,0,books,4,Mama Tried: Traditional Italian Cooking for th...,14.02
88,16.0,fantasy,0,books,2,Masks and Shadows,56.40
89,16.0,food and drink,0,books,2,My Paris Kitchen: Recipes and Stories,33.37
90,16.0,young adult,0,books,2,Obsidian (Lux #1),14.86
91,16.0,add a comment,0,books,3,On a Midnight Clear,14.07
96,16.0,history,0,books,2,"Political Suicide: Missteps, Peccadilloes, Bad...",36.28
98,16.0,fantasy,0,books,5,Princess Between Worlds (Wide-Awake Princess #5),13.34